### ISSUE TITLE
Instructions to compile for Android

### ISSUE THREAD

**Issue by srikanth007m** [nihui/valgrind-android#11]
@nihui @zchrissirhcz Please provide intructions on how to compile for Android with newer version of Valgrind. 

Thanks in advance.

**Comment by srikanth007m** [comment]
I am getting segfault just for trying with memcheck to see if it runs or not. 

tmp/valgrind-3.17.0-android/valgrind/bin # ./valgrind
Segmentation fault

**Comment by zchrissirhcz** [comment]
The build steps is in https://github.com/nihui/valgrind-android/blob/master/.github/workflows/release.yml
